export default {
  GET_NEWS_REQUEST: 'GET_NEWS_REQUEST',
  GET_NEWS_SUCCESS: 'GET_NEWS_SUCCESS',
  GET_NEWS_ERROR: 'GET_NEWS_ERROR',

  //---------------------------------
  GET_NEWS_RECORD_REQUEST: 'GET_NEWS_RECORD_REQUEST',
  GET_NEWS_RECORD_SUCCESS: 'GET_NEWS_RECORD_SUCCESS',
  GET_NEWS_RECORD_ERROR: 'GET_NEWS_RECORD_ERROR',
  //---------------------------------
};
