export default {
  // --- GET NEWS LIST --- //
  GET_NEWS_REQUEST: 'GET_NEWS_REQUEST',
  GET_NEWS_SUCCESS: 'GET_NEWS_SUCCESS',
  GET_NEWS_ERROR: 'GET_NEWS_ERROR',
  // --- GET NEWS LIST --- //

  // --- GET NEWS RECORD BY ID --- //
  GET_NEWS_RECORD_REQUEST: 'GET_NEWS_RECORD_REQUEST',
  GET_NEWS_RECORD_SUCCESS: 'GET_NEWS_RECORD_SUCCESS',
  GET_NEWS_RECORD_ERROR: 'GET_NEWS_RECORD_ERROR',
  // --- GET NEWS RECORD BY ID --- //

  // --- ADD NEWS FROM MODAL WINDOW --- //
  ADD_NEWS_RECORD_REQUEST: 'ADD_NEWS_RECORD_REQUEST',
  ADD_NEWS_RECORD_SUCCESS: 'ADD_NEWS_RECORD_SUCCESS',
  ADD_NEWS_RECORD_ERROR: 'ADD_NEWS_RECORD_ERROR',
  // --- ADD NEWS FROM MODAL WINDOW --- //

  // --- DELETE NEWS RECORD BY ID --- //
  DELETE_NEWS_RECORD_REQUEST: 'DELETE_NEWS_RECORD_REQUEST',
  DELETE_NEWS_RECORD_SUCCESS: 'DELETE_NEWS_RECORD_SUCCESS',
  DELETE_NEWS_RECORD_ERROR: 'DELETE_NEWS_RECORD_ERROR',
  // --- DELETE NEWS RECORD BY ID --- //

  // --- SET CURRENT PAGE --- //
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
};
